name: Weather Routing Tool Workflow

on:
  # push:
  #   branches:
  #     - 'MakeWRTImportable'
  #   paths:
  #     - 'WeatherRoutingTool/**'
  workflow_dispatch:

jobs:
  lint:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
        #python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          # install dependencies required by cartopy
          apt-get update && apt-get -y install libproj-dev proj-data proj-bin libgeos-dev
          python -m pip install --upgrade pip
          cd WeatherRoutingTool
          if [ -f requirements.test.txt ]; then pip install -r requirements.test.txt; fi
      #- name: Install flake8
      #  run: pip install flake8
#      - name: Run flake8
#        run: |
#          flake8 --max-line-length=120 WeatherRoutingTool
      - name: Run pytest
        run: |
          pytest WeatherRoutingTool/tests
        # uses: suo/flake8-github-action@releases/v1
        # with:
        #   # NOTE: this needs to be the same as the job name
        #   checkName: 'lint'
      # - name: Lint with Black
      #   #uses: psf/black@stable
      #   # available black versions: 23.1.0 -> 23.3.0 -> 23.7.0 <- latest
      #   uses: psf/black@23.3.0
      #   with:
      #     options: "--check --line-length 120 --verbose --diff"
      #     src: "WeatherRoutingTool/WeatherRoutingTool"
      # - name: Install pytest
      #   run: |
      #     pip install pytest
      # - name: Test with pytest
      #   run: |
      #     pytest WeatherRoutingTool/tests/
